common:
  use_cuda: !!bool False

model:
  model_name_or_path: './checkpoint' # facebook/wav2vec2-base-960h
  classes: [Angry, Happy, Neutral, Sad, Surprise]

classifier:
  num_labels: 5
  hidden_size: 768
  proj_size: 256
  final_dropout: 0.1
